alter function public.gerar_numero_comanda() set search_path = pg_catalog, public;
alter function public.registrar_movimentacao_estoque(uuid, character varying, integer, numeric, text, character varying, uuid, uuid, uuid, uuid) set search_path = pg_catalog, public;
alter function public.calcular_totais_pacote(uuid) set search_path = pg_catalog, public;
alter function public.trigger_recalcular_pacote() set search_path = pg_catalog, public;
alter function public.verificar_permissao(uuid, character varying, character varying) set search_path = pg_catalog, public;
alter function public.registrar_log_acao(uuid, character varying, character varying, uuid, jsonb, jsonb, character varying, text) set search_path = pg_catalog, public;
alter function public.limpar_sessoes_expiradas() set search_path = pg_catalog, public;
alter function public.sincronizar_comandas_existentes() set search_path = pg_catalog, public;
alter function public.fn_buscar_horario_disponivel(date, uuid, uuid, character varying) set search_path = pg_catalog, public;
alter function public.validar_promocao(uuid, date, time without time zone, character varying, numeric, uuid) set search_path = pg_catalog, public;
alter function public.calcular_desconto_promocao(uuid, numeric) set search_path = pg_catalog, public;
alter function public.criar_etapa_padrao_servico(uuid, character varying, integer) set search_path = pg_catalog, public;
alter function public.verificar_conflito_horario_v2(uuid, date, time without time zone, time without time zone, uuid, uuid) set search_path = pg_catalog, public;
alter function public.fn_horarios_vagos(uuid, date, integer) set search_path = pg_catalog, public;
alter function public.calcular_duracao_servico(uuid) set search_path = pg_catalog, public;
alter function public.update_servico_etapas_updated_at() set search_path = pg_catalog, public;
alter function public.trigger_atualizar_duracao_servico() set search_path = pg_catalog, public;
alter function public.verificar_conflito_horario(uuid, date, time without time zone, time without time zone, uuid) set search_path = pg_catalog, public;
alter function public.calcular_duracao_total_comanda(bigint) set search_path = pg_catalog, public;
alter function public.criar_agendamento_da_comanda(bigint) set search_path = pg_catalog, public;
alter function public.trigger_criar_agendamento_comanda() set search_path = pg_catalog, public;
alter function public.update_comandas_updated_at() set search_path = pg_catalog, public;
alter function public.set_numero_comanda() set search_path = pg_catalog, public;
alter function public.update_agendamentos_updated_at() set search_path = pg_catalog, public;
alter function public.fn_gravar_agendamento(jsonb) set search_path = pg_catalog, public;
alter function public.update_updated_at_column() set search_path = pg_catalog, public;

revoke all on function public.gerar_numero_comanda() from public, anon, authenticated;
revoke all on function public.registrar_movimentacao_estoque(uuid, character varying, integer, numeric, text, character varying, uuid, uuid, uuid, uuid) from public, anon, authenticated;
revoke all on function public.calcular_totais_pacote(uuid) from public, anon, authenticated;
revoke all on function public.trigger_recalcular_pacote() from public, anon, authenticated;
revoke all on function public.verificar_permissao(uuid, character varying, character varying) from public, anon, authenticated;
revoke all on function public.registrar_log_acao(uuid, character varying, character varying, uuid, jsonb, jsonb, character varying, text) from public, anon, authenticated;
revoke all on function public.limpar_sessoes_expiradas() from public, anon, authenticated;
revoke all on function public.sincronizar_comandas_existentes() from public, anon, authenticated;
revoke all on function public.fn_buscar_horario_disponivel(date, uuid, uuid, character varying) from public, anon, authenticated;
revoke all on function public.validar_promocao(uuid, date, time without time zone, character varying, numeric, uuid) from public, anon, authenticated;
revoke all on function public.calcular_desconto_promocao(uuid, numeric) from public, anon, authenticated;
revoke all on function public.criar_etapa_padrao_servico(uuid, character varying, integer) from public, anon, authenticated;
revoke all on function public.verificar_conflito_horario_v2(uuid, date, time without time zone, time without time zone, uuid, uuid) from public, anon, authenticated;
revoke all on function public.fn_horarios_vagos(uuid, date, integer) from public, anon, authenticated;
revoke all on function public.calcular_duracao_servico(uuid) from public, anon, authenticated;
revoke all on function public.update_servico_etapas_updated_at() from public, anon, authenticated;
revoke all on function public.trigger_atualizar_duracao_servico() from public, anon, authenticated;
revoke all on function public.verificar_conflito_horario(uuid, date, time without time zone, time without time zone, uuid) from public, anon, authenticated;
revoke all on function public.calcular_duracao_total_comanda(bigint) from public, anon, authenticated;
revoke all on function public.criar_agendamento_da_comanda(bigint) from public, anon, authenticated;
revoke all on function public.trigger_criar_agendamento_comanda() from public, anon, authenticated;
revoke all on function public.update_comandas_updated_at() from public, anon, authenticated;
revoke all on function public.set_numero_comanda() from public, anon, authenticated;
revoke all on function public.update_agendamentos_updated_at() from public, anon, authenticated;
revoke all on function public.fn_gravar_agendamento(jsonb) from public, anon, authenticated;
revoke all on function public.update_updated_at_column() from public, anon, authenticated;

grant execute on function public.gerar_numero_comanda() to service_role;
grant execute on function public.registrar_movimentacao_estoque(uuid, character varying, integer, numeric, text, character varying, uuid, uuid, uuid, uuid) to service_role;
grant execute on function public.calcular_totais_pacote(uuid) to service_role;
grant execute on function public.trigger_recalcular_pacote() to service_role;
grant execute on function public.verificar_permissao(uuid, character varying, character varying) to service_role;
grant execute on function public.registrar_log_acao(uuid, character varying, character varying, uuid, jsonb, jsonb, character varying, text) to service_role;
grant execute on function public.limpar_sessoes_expiradas() to service_role;
grant execute on function public.sincronizar_comandas_existentes() to service_role;
grant execute on function public.fn_buscar_horario_disponivel(date, uuid, uuid, character varying) to service_role;
grant execute on function public.validar_promocao(uuid, date, time without time zone, character varying, numeric, uuid) to service_role;
grant execute on function public.calcular_desconto_promocao(uuid, numeric) to service_role;
grant execute on function public.criar_etapa_padrao_servico(uuid, character varying, integer) to service_role;
grant execute on function public.verificar_conflito_horario_v2(uuid, date, time without time zone, time without time zone, uuid, uuid) to service_role;
grant execute on function public.fn_horarios_vagos(uuid, date, integer) to service_role;
grant execute on function public.calcular_duracao_servico(uuid) to service_role;
grant execute on function public.update_servico_etapas_updated_at() to service_role;
grant execute on function public.trigger_atualizar_duracao_servico() to service_role;
grant execute on function public.verificar_conflito_horario(uuid, date, time without time zone, time without time zone, uuid) to service_role;
grant execute on function public.calcular_duracao_total_comanda(bigint) to service_role;
grant execute on function public.criar_agendamento_da_comanda(bigint) to service_role;
grant execute on function public.trigger_criar_agendamento_comanda() to service_role;
grant execute on function public.update_comandas_updated_at() to service_role;
grant execute on function public.set_numero_comanda() to service_role;
grant execute on function public.update_agendamentos_updated_at() to service_role;
grant execute on function public.fn_gravar_agendamento(jsonb) to service_role;
grant execute on function public.update_updated_at_column() to service_role;

alter table public.webhook_log enable row level security;
drop policy if exists webhook_log_insert on public.webhook_log;
revoke all privileges on public.webhook_log from public, anon, authenticated;
grant all privileges on public.webhook_log to service_role;
