create index if not exists idx_abertura_caixa_aberto_por on public.abertura_caixa(aberto_por);
create index if not exists idx_agendamentos_blocos_agendamento_id on public.agendamentos_blocos(agendamento_id);
create index if not exists idx_agendamentos_blocos_etapa_id on public.agendamentos_blocos(etapa_id);
create index if not exists idx_comanda_itens_pacote_cliente_id on public.comanda_itens(pacote_cliente_id);
create index if not exists idx_comanda_itens_profissional_id on public.comanda_itens(profissional_id);
create index if not exists idx_comanda_pacote_consumos_pacote_cliente_id on public.comanda_pacote_consumos(pacote_cliente_id);
create index if not exists idx_comandas_criado_por on public.comandas(criado_por);
create index if not exists idx_comandas_desconto_aplicado_por on public.comandas(desconto_aplicado_por);
create index if not exists idx_comandas_fechado_por on public.comandas(fechado_por);
create index if not exists idx_comandas_profissional_id on public.comandas(profissional_id);
create index if not exists idx_comissoes_criado_por on public.comissoes(criado_por);
create index if not exists idx_contas_fixas_pagamentos_pago_por on public.contas_fixas_pagamentos(pago_por);
create index if not exists idx_estoque_movimentacoes_comanda_id on public.estoque_movimentacoes(comanda_id);
create index if not exists idx_estoque_movimentacoes_estornada_por on public.estoque_movimentacoes(estornada_por);
create index if not exists idx_estoque_movimentacoes_usuario_id on public.estoque_movimentacoes(usuario_id);
create index if not exists idx_fechamentos_caixa_fechado_por on public.fechamentos_caixa(fechado_por);
create index if not exists idx_fechamentos_caixa_reaberto_por on public.fechamentos_caixa(reaberto_por);
create index if not exists idx_fundo_caixa_updated_by on public.fundo_caixa(updated_by);
create index if not exists idx_fundo_caixa_movimentacoes_criado_por on public.fundo_caixa_movimentacoes(criado_por);
create index if not exists idx_pacote_consumos_criado_por on public.pacote_consumos(criado_por);
create index if not exists idx_pacote_consumos_servico_id on public.pacote_consumos(servico_id);
create index if not exists idx_pacote_consumos_unit_id on public.pacote_consumos(unit_id);
create index if not exists idx_pacotes_cliente_servico_id on public.pacotes_cliente(servico_id);
create index if not exists idx_produto_operacoes_criado_por on public.produto_operacoes(criado_por);
create index if not exists idx_servicos_produtos_produto_id on public.servicos_produtos(produto_id);
create index if not exists idx_transacoes_criado_por on public.transacoes(criado_por);
create index if not exists idx_transacoes_profissional_id on public.transacoes(profissional_id);

drop index if exists public.idx_agendamentos_aux_data;
drop index if exists public.idx_agendamentos_prof_data;
drop index if exists public.idx_cie_auxiliar;
drop index if exists public.idx_cie_item;
drop index if exists public.idx_cie_profissional;
drop index if exists public.idx_cie_etapa;
